language: node_js
node__js: 
  - lts/*
os:
  - 'linux'
  - 'osx'
  - 'windows'
install:
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov